# Nadine Stair

## I'd Pick More Daisies

> If I had my life to live over,  
>             I'd try to make more mistakes next time.  
>                  I would relax. I would limber up.  
>       I would be sillier than I have on this trip.  
>       I would be crazier. I would be less hygienic.  
>    I would take more chances, I would take more trips.  
>   I would climb more mountains, swim more rivers,  
>           and watch more sunsets.  
> I would burn more gasoline. I would eat more ice cream and less beans.  
>   I would have more actual troubles and fewer imaginary ones.  
>          You see, I am one of those people who lives  
>     prophylactically and sensibly and sanely,  
>      hour after hour, day after day.  
>   
>                Oh, I have had my moments  
>   And if I had it to do over again, I'd have more of them.  
>         In fact, I'd try to have nothing else.  
>         Just moments,one after another.  
>       Instead of living so many years ahead each day.  
>      I have been one of those people who never go anywhere  
>     without a thermometer, a hot water bottle, a gargle, a  
>           raincoat, and a parachute.  
>   
>     If I had to do it over again, I would go places and do things.  
>                        I'd travel lighter than I have.  
>       If I had my life to live over, I would start barefooted  
>          earlier in the spring and stay that way later in the fall.  
>            I would play hooky more. I wouldn't make such good grades  
>                 except by accident.  
>                    I would ride on merry-go-rounds.  
>   
>                         I'd pick more daisies!  
> 

## 我会采更多的雏菊

> 如果我能够从头活过，  
> 我会试着犯更多的错。  
>   
> 我会放松一点，我会灵活一点。  
> 我会比这一趟过得傻。  
> 很少有什么事情能让我当真。  
>   
> 我会疯狂一些，我会少讲点卫生。  
> 我会冒更多的险。我会更经常的旅行。  
> 我会爬更多的山，游更多的河，看更多的日落。  
> 我会多吃冰激凌，少吃豆子。   
> 我会惹更多的麻烦，可是不在想象中担忧。  
>   
> 你看，我小心翼翼地稳健地理智地活着。  
> 一个又一个小时，一天又一天。  
>   
> 噢，我有过难忘的时刻。  
> 如果我能够重来一次，我会要更多这样的时刻。  
>   
> 事实上，我不需要别的什么，  
> 仅仅是时刻，一个接着一个。  
> 而不是每天都操心着以后的漫长日子。  
>   
> 我曾经不论到哪里都不忘记带上：  
> 温度计，热水壶，雨衣和降落伞。  
>   
> 如果我能够重来一次，  
> 我会到处走走，什么都试试，并且轻装上阵。  
> 如果我能够重头活过，  
> 我会延长打赤脚的时光。  
> 从尽早的春天到尽晚的秋天。  
>   
> 我会更经常的逃学。  
> 我不会考那么高的分数，除非是一不小心。   
> 我会多骑些旋转木马，  
> 我会采更多的雏菊。  


