# Robert Penn Warren（罗伯特·潘·沃伦）

## 我一路走来

> 我一路走来，   
> 坐在树影里，  
> 膝上放着书，但一无所思。  
> 我凝视着    
> 小儿子在下午的阳光中嬉戏。  
>   
> 痉挛，吵闹  
> 夜起伏呼吸，燃烧，而星星  
> 陨落。我记得什么？  
> 我听见沼地的枭鹰整夜呼唤，  
> 而远处汽车的前灯扫过房间。  
>   
> 我是个阴暗狡黠的家伙，  
> 我从阴影里朝外看，  
> 你一绺绺头发闪着阳光，  
> 我看着你在阳光下嬉戏，  
> 儿子，请你教我白昼的方式。  
>   （赵毅衡译）  

## WAYS OF DAY

> I have come all this way.  
> I am sitting in the shade.  
> Book on knee and mind on nothing,  
> I now fix my gaze  
> On my small son playing in the afternoon's blaze.  
>   
> Convulsive and cantankerous,  
> Night heaved, and burning, the star  
> Fell. What do I remember?  
> I heard the swamp owl, night-long, call.  
> The far car's headlight swept the room wall.  
>   
> I am the dark and tricky one.  
> I am watching from my shade.  
> Your tousled hair-tips prickle the sunlight.  
> I watch you at your sunlit play.  
> Teach me, my son, the ways of day.  

## 世事沧桑话鸣鸟

> 那只是一只鸟在晚上鸣叫，认不出是什么鸟，  
> 当我从泉边取水回来，走过满是石头的牧场，  
> 我站得那么静，头上的天空和水桶里的天空一样静。  
>   
> 多少年过去，多少地方多少脸都淡漠了，有的人已谢世，  
> 而我站在远方，夜那么静，我终于肯定  
> 我最怀念的，不是那些终将消逝的东西， 而是鸟鸣时那种宁静。  
>    （赵毅衡 译）

   
## Ornithology in a World of Flux

> It was only a bird call at evening, unidentified,  
> As I came from the spring with water, across the rocky back-pasture;  
> But so still I stood sky above was not stiller than sky in pail-water.  
>   
> Years pass, all places and faces fade, some people have died,  
> And I stand in a far land, the evening still, and am at last sure  
> That I miss more that stillness at bird-call than some things  
> that were to fail later.  




