---
title: 'In Search of Lost Time: 2016'
author: Jiangtang Hu
date: '2017-05-04'
slug: in-search-of-lost-time-2016
categories:
  - data mining
  - Machine Learning
  - R
  - Python
tags:
  - R
  - Python
  - Spark
  - machine learning
---

2016 was gone, and I didn't even leave one single blog post. An obvious inference should be, 2016 doesn't exist...

2016 was a year of struggle for me as a SAS programmer. I earn my bread mostly using SAS, but is a SAS programmer like me cool? It's not a silly question. Lots of SAS programmers feel the crunch.

So, in 2016, I 

* [learned some Python](https://github.com/Jiangtang/Homer-networkX),
* attended [Pydata Carolinas](https://pydata.org/carolinas2016/),
* learned some Spark, and got certified by edX somehow with all the bubble words in the title, [Distributed Machine Learning with Apache Spark](https://courses.edx.org/certificates/85c0f27c305b49abafee8da0005191a1),
* learned some math, [Linear Algebra](http://math.mit.edu/~gs/linearalgebra/),
* learned more math, [Probability](https://projects.iq.harvard.edu/stat110/youtube), 
* learned even more math, [Numerical Analysis](http://www4.ncsu.edu/~ctk/ma580.html), and
* didn't update one single blog post, because all my spare time and coffee making time were simply run out.

I feel much better after one year of burying my head in the sand. Keep tuned, 2017.